source 'http://rubygems.org'

gem 'rails', '3.0.5'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

platforms :ruby do
  gem 'mysql2'
  gem 'pg'
end

platforms :jruby do
  gem 'activerecord-jdbc-adapter'
  gem 'jdbc-mysql', :require => false
  gem 'jdbc-postgres', :require => false
  gem 'warbler'
end

gem "devise"
gem "jquery-rails"
gem 'prawn', :git => "git://github.com/sandal/prawn.git", :tag => '0.11.1', :submodules => true
gem 'spreadsheet'
gem 'rubyzip'
gem 'mail'
gem 'jruby-openssl'
gem 'resque'
gem 'redis'
gem 'redis-namespace'
gem 'vegas'
gem 'trinidad'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
