# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'lib/pdf_queue'
require 'lib/xls_queue'
require 'lib/compress_queue'
require 'lib/mail_queue'
require 'lib/hmis'
require 'resque'
require 'resque/tasks'

CET::Application.load_tasks
